apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  name: otel-collector # IMPORTANT:  Name of the ExtensionService resource
  namespace: vsdm2 # IMPORTANT: ExtensionService in 'projectcontour' namespace
spec:
  protocol: h2c # Assuming your collector supports gRPC in cleartext (h2c)
  services:
    - name: otel-collector-svc # IMPORTANT: Kubernetes Service name in 'vsdm2' namespace
      port: 4317
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    tracing:
      # Whether to send the namespace and instance where envoy is located to open, the default is true.
      #includePodDetail: true
      # The extensionService and namespace and name defined above in the format of namespace/name.
      extensionService: vsdm2/otel-collector
      # The service name that envoy sends to openTelemetry-collector, the default is contour.
      serviceName: contour
      # A custom set of tags.
      customTags:
      # envoy will send the tagName to the collector.
      - tagName: zeta-guard
        # fixed tag value.
        literal: ingress-contour
