kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  - containerPort: 30090
    hostPort: 30090
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 8888
    hostPort: 8888
  - containerPort: 8181
    hostPort: 8181
  - containerPort: 4444
    hostPort: 4444
  - containerPort: 4445
    hostPort: 4445
  - containerPort: 4317
    hostPort: 4317
  - containerPort: 4318
    hostPort: 4318
  - containerPort: 9090
    hostPort: 9090
