apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-pep
  namespace: vsdm2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey-pep
  template:
    metadata:
      labels:
        app: valkey-pep
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 18081
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-pep-svc
  namespace: vsdm2
spec:
  selector:
    app: valkey-pep
  ports:
  - protocol: TCP
    port: 10081
    targetPort: 18081