apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-18T11:44:53Z"
  generateName: rs-vsdm2-deployment-646b6cf478-
  labels:
    app: rs-vsdm2
    pod-template-hash: 646b6cf478
  name: rs-vsdm2-deployment-646b6cf478-vtrdn
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rs-vsdm2-deployment-646b6cf478
    uid: 608609e2-bdf2-4a8c-ab8e-6a4dc78e4d0a
  resourceVersion: "8711"
  uid: 242e2690-d2bb-4952-afc3-1036977d9a21
spec:
  containers:
  - image: rs-vsdm2-app
    imagePullPolicy: IfNotPresent 
    name: rs-vsdm2-container
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fnzm9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: zeta-guard-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fnzm9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-18T11:44:55Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-02-18T11:44:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-02-18T11:44:53Z"
    message: 'containers with unready status: [rs-vsdm2-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-02-18T11:44:53Z"
    message: 'containers with unready status: [rs-vsdm2-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-02-18T11:44:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: rs-vsdm2-app
    imageID: ""
    lastState: {}
    name: rs-vsdm2-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Back-off pulling image "rs-vsdm2-app": ErrImagePull: failed to pull
          and unpack image "docker.io/library/rs-vsdm2-app:latest": failed to resolve
          reference "docker.io/library/rs-vsdm2-app:latest": pull access denied, repository
          does not exist or may require authorization: server message: insufficient_scope:
          authorization failed'
        reason: ImagePullBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fnzm9
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.23.0.3
  hostIPs:
  - ip: 172.23.0.3
  phase: Pending
  podIP: 10.244.1.2
  podIPs:
  - ip: 10.244.1.2
  qosClass: BestEffort
  startTime: "2025-02-18T11:44:53Z"
