apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-19T07:56:05Z"
  generateName: rs-vsdm2-deployment-6569fb55c5-
  labels:
    app: rs-vsdm2
    pod-template-hash: 6569fb55c5
  name: rs-vsdm2-deployment-6569fb55c5-9jxpx
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rs-vsdm2-deployment-6569fb55c5
    uid: 1522a4f5-d46e-481e-9f90-f0d59d395ef8
  resourceVersion: "2293"
  uid: 6a8fd2ee-d0cf-470e-8344-14064adb6cdd
spec:
  containers:
  - image: rs-vsdm2-app:latest
    imagePullPolicy: IfNotPresent
    name: rs-vsdm2
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-46f4t
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: zeta-guard-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-46f4t
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-19T07:56:08Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-02-19T07:56:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-02-19T07:56:05Z"
    message: 'containers with unready status: [rs-vsdm2]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-02-19T07:56:05Z"
    message: 'containers with unready status: [rs-vsdm2]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-02-19T07:56:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: rs-vsdm2-app:latest
    imageID: ""
    lastState: {}
    name: rs-vsdm2
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'failed to pull and unpack image "docker.io/library/rs-vsdm2-app:latest":
          failed to resolve reference "docker.io/library/rs-vsdm2-app:latest": pull
          access denied, repository does not exist or may require authorization: server
          message: insufficient_scope: authorization failed'
        reason: ErrImagePull
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-46f4t
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.2
  hostIPs:
  - ip: 172.18.0.2
  phase: Pending
  podIP: 10.244.1.2
  podIPs:
  - ip: 10.244.1.2
  qosClass: BestEffort
  startTime: "2025-02-19T07:56:05Z"
