kind: Cluster
apiVersion: kind.x-k8s.io/v1beta3
nodes:
- role: control-plane
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 82   # Dynamischer Ingress-Port
  - containerPort: 443
    hostPort: 8243 # Dynamischer Ingress-Port for HTTPS

