@startuml "discovery and configuration"
autonumber "(00)"
skinparam defaultFontSize 10
skinparam defaultFontName Helvetica
skinparam DefaultMonospacedFontName Courier
skinparam lengthAdjust none
skinparam sequenceReferenceBackgroundColor White
skinparam SequenceReferenceFontSize 12
/'skinparam SequenceReferenceFontStyle bold
'/


!pragma teoz true

Actor User
box "LEI" #GhostWhite
  box "Primärsystem" #Lavender
    box "ZETA Client" #SandyBrown
      participant Client as "ZETA\nClient"
    end box
    participant TPM as "TPM"
  end box
  participant Konnektor as "Konnektor or\nTI-Gateway"
  participant SMB as "SM(C)-B"
end box

box "Anbieter" #TECHNOLOGY
  box "ZETA Guard" #SandyBrown
    participant HP as "PEP\nhttp Proxy"
    participant AuthS as "PDP\nAuthorization Server" 
    participant PE as "PDP\nPolicy Engine"
  end box
    box TI 2.0 Dienst #DarkSeaGreen
      participant RS as "Resource\nServer"
    end box
end box

group ZETA Client has Resource Server FQDN (RS-FQDN)
  activate Client
  Client -> HP: GET /.well-known/oauth-protected-resource Host: RS-FQDN
  activate HP
  HP --> Client: Client: 200 OK; json body with Well-Known json Document (RFC draft-ietf-oauth-resource-metadata)
  deactivate HP
  Client -> Client: Update Resource Server and ZETA Guard Configuration
  Client -> AuthS: GET /.well-known/oauth-authorization-server Host: AuthS-FQDN
  activate AuthS
  AuthS --> Client: 200 OK; json body with Well-Known json Document (RFC8414)
  deactivate AuthS
  Client -> Client: Update Authorization Server Configuration
  
  note right of Client
    Offene Fragen:
    - Werden die Well-known JSON Dokumente signiert?
    - Wenn ja, welches Zertifikat wird für die Signatur verwendet?
    - Wie wird die Signatur überprüft?
  end note
end

@enduml