[tool.poetry]
name = "fastapi-pip-pap"
version = "0.1.0"
description = ""
authors = ["gem-cp <christian.plagens@gematik.de>"]
readme = "README.adoc"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
