= fastapi-pip-pap

This fastapi-pip-pap is intended for local development and testing. It is not intended for production use.

== Usage

Install https://python-poetry.org[Python Poetry] 

[source,sh]
----
pipx install poetry
----

Install the dependencies and switch to virtual environment
[source,sh]
----
poetry install
poetry shell
----

The files to start the service in the `/components/fastapi-pip-pap` directory of the project.
You need to `create bundle.tar.gz` files and place them in the `<config.yaml bundle_storage_path>/<application>/<version>/<bundleType>` directory.
Example: `/var/tmp/fastapi-pip-pap/KIM/2.0/pap/bundle.tar.gz`

The following command starts pip-pap-service on localhost:8200.
[source,sh]
----
python fastapi-pip-pap.py
----

or as docker container on localhost:8080
[source,sh]
----
docker-compose up -d
----

To retrieve the bundle file you can use the following curl command:
[source,sh]
----
curl -v -H "If-None-Match: yourETag" http://127.0.0.1:8080/policies/KIM/latest --output bundle.tar.gz
----

You can also use an https://www.openpolicyagent.org/docs/latest/#running-opa[OPA client]

== Configuration

The config.yaml file contains the following configuration options:
[source,yaml]
----
# Base path for bundle storage
bundle_storage_path: /var/tmp/fastapi-pip-pap

# logging configuration
logging:
  loglevel: DEBUG
  log_to_console: True
  log_to_file: False
  # If log _to_file is True then the logfile is: <service_name>.log
  service_name: fastapi-pip-pap
----

== Requirements

* docker
* docker-compose
* python3
* uvicorn