= pip-pap-service

This pip-pap-service is intended for local development and testing. It is not intended for production use.

== Usage

Install https://python-poetry.org[Python Poetry] 

[source,sh]
----
pipx install poetry
----

Install the dependencies and switch to virtual environment
[source,sh]
----
poetry install
poetry shell
----

The files to start the service are in the `/components/pip-pap-service/src` directory of the project.
You need to `create bundle.tar.gz` files and place them in the `<config.yaml bundle_storage_path>/<application>/<version>/<bundleType>` directory.
Example: `/var/tmp/pip-pap-service/KIM/2.0/pap/bundle.tar.gz`

The following command starts pip-pap-service on localhost:5000.
[source,sh]
----
python pip-pap-service.py
----

or with uWSGI on localhost:8900
[source,sh]
----
uwsgi --yaml uwsgi.yaml
----

or as docker container on localhost:8900
----
docker-compose up -d
----

To retrieve the bundle file you can use the following curl command:
----
curl -v -H "If-None-Match: yourETag" http://127.0.0.1:8900/KIM/2.0/pap/bundle.tar.gz --output bundle.tar.gz
----

== Configuration

The config.yaml file contains the following configuration options:
[source,yaml]
----
# Base path for bundle storage
bundle_storage_path: /var/tmp/pip-pap-service

# logging configuration
logging:
  loglevel: DEBUG
  log_to_console: True
  log_to_file: True
  # If log _to_file is True then the logfile is: <service_name>.log
  service_name: pip-pap-service
----

== Requirements

* docker
* docker-compose
* python3
* flask
* uwsgi