apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: vsdm2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "0.5"
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-home-dashboard # Existing dashboard volume mount
          mountPath: /usr/share/grafana/public/dashboards
        - name: grafana-datasource-config # <----- New volumeMount for datasource provisioning
          mountPath: /etc/grafana/provisioning/datasources # Standard Grafana datasource provisioning path
          readOnly: true # Recommended: Datasources are usually read-only from ConfigMap
        env: # <----- Moved 'env' block inside the 'containers[0]' definition
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-home-dashboard # Existing dashboard volume
        configMap:
          name: grafana-dashboard-otel-collector
      - name: grafana-datasource-config # <----- New volume definition for datasource provisioning
        configMap:
          name: grafana-datasource-prometheus # ConfigMap name for datasource provisioning
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: vsdm2
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030 # Optional: Exposed on NodePort for easy access
  type: NodePort # Optional: Exposed on NodePort für einfachen Zugriff
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: vsdm2
data:
  grafana.ini: |-
    [analytics]
    check_for_updates = false

    [log]
    level = info

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [dashboards]
    # Path to the default home dashboard. If this value is empty, then Grafana uses StaticRootPath + "dashboards/home.json"
    default_home_dashboard_path = /usr/share/grafana/public/dashboards/otel-collector-dashboard.json
    
    # end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus # Name of your ConfigMap
  namespace: vsdm2 # Same namespace as Grafana
data:
  datasources.yaml: |-
    # datasources.yaml
    apiVersion: 1

    datasources:
      - name: Prometheus # Name as it will appear in Grafana UI
        type: prometheus # Datasource type: prometheus
        url: http://prometheus-svc.vsdm2.svc.cluster.local:9090 # URL to your Prometheus service
        access: proxy # Access mode (proxy or direct - 'proxy' is generally recommended in Kubernetes)
        isDefault: true # Set to true if you want this to be the default datasource
        editable: true # Set to true if you want to be able to edit it in Grafana UI (usually false for provisioned datasources)
        # Add any other Prometheus-specific settings here if needed, e.g.,
        # basicAuth: false
        # jsonData:
        #   httpMethod: GET
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-otel-collector # Name of your ConfigMap
  namespace: vsdm2 # Same namespace as Grafana
  labels:
    grafana_dashboard: "1" # Important label for Grafana to recognize dashboards
data:
  otel-collector-dashboard.json: |- # Key is the filename, value is the JSON
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": false,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "datasource": {
            "name": "Prometheus",
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum by (http_method) (rate(traces_span_metrics_duration_milliseconds_sum{job=\"otel-collector\"}[1m])) / sum by (http_method)        (rate(traces_span_metrics_duration_milliseconds_count{job=\"otel-collector\"}[1m]))",
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Average Duration in ms",
          "type": "timeseries"
        },
        {
          "datasource": {
            "name": "Prometheus",
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 16,
            "w": 11,
            "x": 12,
            "y": 0
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "editorMode": "code",
              "expr": "rate(process_network_receive_bytes_total[1m])",
              "legendFormat": "Data Volume (Bytes/sec)",
              "range": true,
              "refId": "A",
              "datasource": {
                "name": "Prometheus",
                "type": "prometheus"
              }
            }
          ],
          "title": "Data Volume sent to Prometheus per second (Metrics)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "name": "Prometheus",
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "links": [
                {
                  "title": "Sample Trace in Jaeger",
                  "url": "http://localhost:16686/search?service=envoy-pep-svc&operation=HTTP&tags={\"http.status_code\":\"${__data.fields.http_status_code}\"}&start=${__from}&end=${__to}",
                  "internal": false
                }
              ]
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "datasource": {
                "name": "Prometheus",
                "type": "prometheus"
              },
              "editorMode": "code",
              "expr": "sum by (http_status_code) (rate(traces_span_metrics_calls_total{job=\"otel-collector\"}[1m]))",
              "legendFormat": "{{http_status_code}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Requests per Second pro HTTP Statuscode",
          "type": "timeseries"
        }
      ],
      "preload": false,
      "refresh": "auto",
      "schemaVersion": 40,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "ZETA_dashboard",
      "uid": "ZETA_dashboard-2025-03-03",
      "version": 1,
      "weekStart": ""
    }