{
 "title": "ZETA_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Average Duration in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_method,service_name) (rate(traces_span_metrics_duration_milliseconds_sum{job=\"otel-collector\"}[1m])) / sum by (http_method,service_name)        (rate(traces_span_metrics_duration_milliseconds_count{job=\"otel-collector\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Volume sent to Prometheus per second (Metrics)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Second pro HTTP Statuscode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"envoy-pep-svc\"}[1m]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}