apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: vsdm2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-role-binding
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: vsdm2
roleRef:
  kind: ClusterRole
  name: prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: vsdm2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        - "--web.enable-remote-write-receiver"  # for prometheusremotewrite from otel-collector
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
          - name: prometheus-config-vol
            mountPath: /etc/prometheus
      volumes: # <----- Add volumes
      - name: prometheus-config-vol # Volume name (must match volumeMounts.name)
        configMap:
          name: prometheus-config # ConfigMap name (must match ConfigMap metadata.name)
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: vsdm2
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090 # Optional: Exposed auf NodePort für einfachen Zugriff
  type: NodePort # Optional: Exposed auf NodePort für einfachen Zugriff
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: vsdm2
data:
  prometheus.yaml: |
    global:
      scrape_interval:     5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'prometheus' # Default Prometheus self-monitoring job (keep this)
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'otel-collector' # <---- ADD THIS JOB to scrape otel-collector
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__address__] # Target the address:port of the endpoint
          action: keep
          regex: ^.*:9090$  # Explicitly match any character before :9090 at the end of the address
