apiVersion: v1
kind: Namespace
metadata:
  name: vsdm2 # Use the same namespace as your otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: vsdm2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest # All-in-one image for simplicity
        ports:
        - containerPort: 16686 # Jaeger UI port
          name: jaeger-ui
          protocol: TCP
        - containerPort: 14250 # Jaeger gRPC Collector port
          name: jaeger-grpc
          protocol: TCP
        - containerPort: 14268 # Jaeger HTTP Collector port
          name: jaeger-http
          protocol: TCP
        - containerPort: 5775  # Jaeger Agent compact protocol
          name: ja-compact
          protocol: UDP
        - containerPort: 5778  # Jaeger Agent config port
          name: ja-config
          protocol: TCP
        - containerPort: 6831  # Jaeger Agent binary thrift protocol
          name: ja-binary-tp
          protocol: UDP
        - containerPort: 6832  # Jaeger Agent compact thrift protocol
          name: ja-compact-tp
          protocol: UDP
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-svc
  namespace: vsdm2
spec:
  selector:
    app: jaeger
  ports:
  - protocol: TCP
    port: 16686
    targetPort: jaeger-ui
    name: jaeger-ui
  type: ClusterIP # Use ClusterIP for internal access, or LoadBalancer/NodePort for external
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-svc # <----- Jaeger COLLECTOR Service Name
  namespace: vsdm2
spec:
  selector:
    app: jaeger # Selektiert die Jaeger-Pods
  ports:
  - protocol: TCP
    port: 14250      # Service-Port (kann sich von targetPort unterscheiden)
    targetPort: jaeger-grpc # Ziel ist der jaeger-grpc-Portname im Pod
    name: jaeger-grpc-collector
  type: ClusterIP