# pip-pap-service configuration file

# Base path for bundle storage
bundle_storage_path: /var/tmp/gemini-pip-pap

# logging configuration
logging:
  log_level: INFO
  log_to_console: True
  log_to_file: True
  # If log _to_file is True then the logfile is: <service_name>.log
  service_name: gemini-pip-pap