@startuml "ZT_Cluster_GitOps_CD_Process"
title ZT Cluster GitOps CD Process

actor "Zero Trust Developer" as ZT
actor "Gematik" as GEM
actor "TI 2.0 Service Provider" as TSP

rectangle "Git Repository" as GIT
rectangle "Container Registry" as REG
rectangle "CI Pipeline" as CI
rectangle "Kubernetes Cluster" as K8S

ZT --> CI: develops and\nprovides
GEM --> REG: operates
TSP --> GIT: configures
GEM --> GIT: operates and\nvalidates
TSP --> K8S: operates

CI --> GIT: Manifest Templates
CI --> REG : Docker Images
GIT --> K8S : Manifests
REG --> K8S : Signed Images

note right of K8S: Deploys Changed Manifests\nMonitors Cluster State\nApplies Changes\nPrevents Manual Changes

note left of GIT: Single Source of Truth\nVersioned Configurations

note bottom of REG: signs Images

note top of GIT: Executes Automatic\nDeployments and Tests
@enduml
