version: "3.8"

services:
  pip-pap:
    build: .
    ports:
      - "8600:8600"
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # Mount config file as read-only
    environment:
      PYTHONUNBUFFERED: 1  # Suppress output buffering for logs
