apiVersion: v1
kind: Namespace
metadata:
  name: vsdm2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vsdm2
  namespace: vsdm2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /vsdservice/v1/vsdmbundle # Pfad für Resource Server
        pathType: ImplementationSpecific
        backend:
          service:
            name: envoy-pep-svc # Traffic geht zu Envoy
            port:
              number: 10000
      - path: /query # Neuer Pfad für Prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-svc # Traffic geht zu Prometheus
            port:
              number: 9090
      - path: /hello # Neuer Pfad für Hello world
        pathType: Prefix
        backend:
          service:
            name: hello-world-svc # Traffic geht zu hello-world-svc
            port:
              number: 8888