# pip-pap-service configuration file

# Base path for bundle storage
bundle_storage_path: /var/tmp/pip-pap-service

# logging configuration
logging:
  loglevel: DEBUG
  log_to_console: True
  log_to_file: True
  # If log _to_file is True then the logfile is: <service_name>.log
  service_name: pip-pap-service