apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: envoy-tracing
  namespace: vsdm2
spec:
  podSelector:
    matchLabels:
      app: envoy-pep
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
  - call: "sys_socket"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "int"
    - index: 2
      type: "int"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/local/bin/envoy"
