apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: opa-tracing
  namespace: vsdm2
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/opa"
      matchActions:
      - action: Sigkill
