apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: otel-tracing
  namespace: vsdm2
spec:
  kprobes:
  - call: "sys_socket"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "int"
    - index: 2
      type: "int"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/otelcol-contrib"
