name: Generate Images

on:
  push:
    paths:
      - 'src/plantuml/**'
      - 'src/draw.io/**'

jobs:
  generate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install PlantUML
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml

    - name: Install draw.io
      run: |
        sudo apt-get update
        sudo apt-get install -y xdotool xvfb
        sudo snap install drawio

    - name: Generate images from PlantUML files
      run: |
        find src/plantuml -name '*.puml' | while read -r file; do
          output_dir=$(dirname "$file" | sed 's|^src/plantuml|images|')
          mkdir -p "$output_dir"
          plantuml -tpng "$file" -o "$output_dir"
          plantuml -tsvg "$file" -o "$output_dir"
        done

    - name: Generate images from draw.io files
      run: |
        find src/draw.io -name '*.drawio' | while read -r file; do
          output_dir=$(dirname "$file" | sed 's|^src/draw.io|images|')
          mkdir -p "$output_dir"
          xvfb-run -a drawio -x -f png -o "$output_dir/$(basename "$file" .drawio).png" "$file"
          xvfb-run -a drawio -x -f jpg -o "$output_dir/$(basename "$file" .drawio).jpg" "$file"
        done

    - name: Commit and push generated images
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add images
        git commit -m "Generate images from PlantUML and draw.io files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
