apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-config
  namespace: vsdm2
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
          default_type text/html;
        }
        location /hello {
          root /usr/share/nginx/html;
          default_type text/html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: vsdm2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: nginx:latest # Verwende das offizielle Nginx Image
        ports:
        - containerPort: 80
          name: http
        command: ["/bin/sh", "-c"] # Überschreibe den default Command
        args:
          - >
            echo '<h1>Hello World!</h1>' > /usr/share/nginx/html/index.html &&
            echo '<h1>Hello from /hello</h1>' > /usr/share/nginx/html/hello &&
            nginx -g 'daemon off;'
        # Erkläung der Befehle:
        # 1. echo '<h1>Hello World!</h1>' > /usr/share/nginx/html/index.html:
        #    Erstellt eine einfache HTML Datei (index.html) mit "Hello World!" Inhalt im Nginx Document Root.
        # 2. nginx -g 'daemon off;':
        #    Startet den Nginx Webserver im Vordergrund (daemon off), damit er im Container aktiv bleibt.
        volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-vol
        configMap:
          name: hello-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: vsdm2
spec:
  selector:
    app: hello-world-app
  ports:
  - protocol: TCP
    port: 8888 # Port, auf dem der Service im Cluster erreichbar ist (frei wählbar)
    targetPort: 80 # Port, auf dem der Container (Nginx) lauscht (muss 80 sein, da Nginx default Port)