openapi: 3.0.0
info:
  title: OAuth 2.0 Token Endpoint (RFC 6749 Section 3.2)
  version: 1.0.0
servers:
  - url: https://as.example.com
paths:
  /token:
    post:
      summary: Request an access token
      description: The client exchanges an authorization grant for an access token.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  description: The grant type.
                  enum: [authorization_code, password, client_credentials, refresh_token]
                code:
                  type: string
                  description: The authorization code received in the previous step (for 'authorization_code' grant type only).
                redirect_uri:
                  type: string
                  description: The redirection URI used in the authorization request (for 'authorization_code' grant type only).
                username:
                  type: string
                  description: The resource owner username (for 'password' grant type only).
                password:
                  type: string
                  description: The resource owner password (for 'password' grant type only).
                refresh_token:
                  type: string
                  description: The refresh token, which is used to obtain new access tokens using the same authorization grant as described in Section 6 (for 'refresh_token' grant type only).
                scope:
                  type: string
                  description: The scope of the access request as described by Section 3.3.
                client_id:
                  type: string
                  description: The client identifier issued to the client during the registration process described by Section 2.2.
                client_secret:
                  type: string
                  description: The client secret.
              required:
                - grant_type
      responses:
        200:
          description: Successful response with access token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The access token issued by the authorization server.
                  token_type:
                    type: string
                    description: The type of the token issued.
                  expires_in:
                    type: integer
                    description: The lifetime in seconds of the access token.
                  refresh_token:
                    type: string
                    description: The refresh token, which can be used to obtain new access tokens using the same authorization grant as described in Section 6.
                  scope:
                    type: string
                    description: The scope of the access token as described by Section 3.3.
        400:
          description: Invalid request, such as missing parameters or invalid client credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: An error code.
                  error_description:
                    type: string
                    description: A human-readable description of the error.
                  error_uri:
                    type: string
                    description: A URI pointing to a web page with more information about the error.
