openapi: 3.0.3
info:
  title: Policy Information Point und Policy Administration Point API
  description:  This service is part of the gematik Zero Trust
                Telematikinfrastruktur and implements download
                endpoints for OPA compatible PIP and PAP bundles.
                Open Policy Agents of the Telematikinfrastruktur can
                retrieve bundles (with policies and data) for their
                application and version. The bundles are signed by the
                central administrative OPA instance.
  version: 1.0.0
tags:
  - name: PIP
    description: Policy Information Point
  - name: PAP
    description: Policy Administration Point
servers:
  - url: https://localhost:8080
    description: Local development server
  - url: https://pip-pap-ref.ti-dienste.de
    description: Reference server
  - url: https://pip-pap.ti-dienste.de
    description: Production server
paths:
  /{application}/{version}/{bundleType}_bundle.tar.gz:
    parameters:
      - name: application
        in: path
        description: Application name
        required: true
        schema:
          type: string
      - name: version
        in: path
        description: Version of the application
        required: true
        schema:
          type: string
      - name: bundleType
        in: path
        description: Type of bundle
        required: true
        schema:
          type: string
          enum: [pip, pap, sim_pip, sim_pap]
      - in: header
        name: If-None-Match
        description: The revision of the last retrieved policy bundle
                     (ETag header)
        schema:
          type: string
          description: The revision of the last retrieved policy bundle
    get:
      summary: Retrieve a signed {bundleType} OPA bundle
      description: Retrieve a signed {bundleType} OPA bundle for the
                   given application and version.
                   The service compares the value of the If-None-Match header
                   with the current revision of the bundle.
                   If the bundle has not changed since the last update
                   the server replys with HTTP 304 Not Modified.
      responses:
        '200':
          description: OK
          headers:
            ETag:
              schema:
                type: string
                description: The revision of the policy bundle.
          content:
            application/gzip:
              schema:
                type: string
                format: binary
                description: The signed OPA {bundleType} bundle
        '304':
          description: Not Modified
        '400':
          description: Invalid bundle type
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                example:
                  error: Invalid bundle type.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                example:
                  error: The requested bundle does not exist.
